// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MediaController from "./media_controller"
application.register("media", MediaController)

import NgListsController from "./ng_lists_controller"
application.register("ng-lists", NgListsController)

import ReportersController from "./reporters_controller"
application.register("reporters", ReportersController)

import StaticPagesController from "./static_pages_controller"
application.register("static-pages", StaticPagesController)
